### ISSUE TITLE
MC Edit Crashing on Start... Help pls

### ISSUE THREAD

**Issue by Impartinir** [mcedit/mcedit2#97] opened 2015-05-19 14:19 UTC
![mc edit 2](https://cloud.githubusercontent.com/assets/12514116/7705142/c54ea92a-fe42-11e4-8dec-371efce07df9.PNG)
I dont know what to do. Mc Edit just crashes and i have no Idea how to fix it :C

**Comment by Rubisk** [comment] 2015-05-19 14:42
Duplicate of #78, we'll have to fix this in the code.

**Closed** 2015-05-20 02:44 UTC
