### ISSUE TITLE
MCEDIT build 2.0.0 alpha 919 wont let me start

### ISSUE THREAD

**Issue by Notch8864** [mcedit/mcedit2#195] opened 2016-01-10 01:20 UTC
it told me to send this to the developer, so here you go:

MCEdit version: 2.0.0alpha-919
Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-8-6.2.9200
Processor: AMD64 Family 18 Model 1 Stepping 0, AuthenticAMD

Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True

Driver info:
GL_VERSION: 4.5.13399 Compatibility Profile Context 15.201.1151.0 (4, 5)
GL_VENDOR: 'ATI Technologies Inc.'
GL_RENDERER: 'AMD Radeon HD 6620G'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\worldview\worldview.py", line 574, in paintGL (self is a MinimapWorldView)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 259, in renderScene  
  File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 94, in compile (self is a VertexRenderNode)
  File "mcedit2\util\glutils.py", line 145, in compile (self is a DisplayList)
  File "mcedit2\util\glutils.py", line 150, in _compile (self is a DisplayList)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 108, in draw (self is a VertexRenderNode)
  File "mcedit2\rendering\scenegraph\vertex_array.py", line 47, in drawSelf (self is a VertexRenderNode)
  File "mcedit2\rendering\scenegraph\vertex_array.py", line 81, in drawArrays (self is a VertexRenderNode)
WindowsError: exception: access violation reading 0x0000000000000000

I have no idea what any of this means. So please fix it!!!!!!!

**Comment by codewarrior0** [comment] 2016-01-12 00:18
Duplicate of #110

**Closed by codewarrior0** 2016-01-12 00:18 UTC
