### ISSUE TITLE
mcedit2 error at startup

### ISSUE THREAD

**Issue by supercas240** [mcedit/mcedit2#127] opened 2015-06-19 17:20 UTC
when i start up mcedit alpha 468 i get the following 2 errors:
![2015-06-19 19_15_35-mcedit - world list](https://cloud.githubusercontent.com/assets/12969874/8258753/d6baac58-16b7-11e5-94de-ea0221bd7897.png)
and
![2015-06-19 19_15_49-mcedit - world list](https://cloud.githubusercontent.com/assets/12969874/8258756/db4a0480-16b7-11e5-94bf-a9a6abf22990.png)

also this is my log: 
[INFO][<string>:131]:MCEdit2 version 2.0.0alpha-468 starting...
[INFO][mcedit2.util.profiler:87]:Decorating <function work at 0x0000000004BAB5F8> with work
[INFO][OpenGL.acceleratesupport:13]:OpenGL_accelerate module loaded
[INFO][OpenGL.arrays.arraydatatype:270]:Using accelerated ArrayDatatype
[INFO][mcedit2.util.profiler:87]:Decorating <function loadSections at 0x0000000006BE42E8> with SelectionScene
[INFO][mcedit2.util.profiler:87]:Decorating <function __iter__ at 0x0000000006C184A8> with ChunkUpdate
[INFO][mcedit2.util.profiler:87]:Decorating <function buildChunkMeshes at 0x0000000006C18438> with buildChunkMeshes
[INFO][mcedit2.util.profiler:87]:Decorating <function buildSectionMeshes at 0x0000000006C18588> with buildSectionMeshes
[INFO][mcedit2.util.profiler:87]:Decorating <function __iter__ at 0x0000000006C1A438> with SectionUpdate
[INFO][mcedit2.util.settings:100]:Loading app settings from C:\Users\Cas\Desktop\MCEDIT~1.0AL\MCEdit User Data\mcedit2.ini
[INFO][mcedit2.util.profiler:87]:Decorating <function workOnChunk at 0x0000000006FEEBA8> with SlicedMesh
[INFO][mcedit2.util.minecraftinstall:205]:Checking install at C:\Users\Cas\AppData\Roaming\.minecraft
[INFO][mcedit2.util.minecraftinstall:212]:Found versions:
[u'1.7.2', u'1.7.2-Forge10.12.0.1015', u'1.7.2-Forge10.12.2.1147', u'1.7.2-LiteLoader1.7.2', u'1.7.2-OptiFine_HD_U_D4', u'1.8', u'1.8-Forge11.14.1.1334']
[INFO][mcedit2.util.minecraftinstall:205]:Checking install at C:\Users\Cas\AppData\Roaming\.minecraft
[INFO][mcedit2.util.minecraftinstall:212]:Found versions:
[u'1.7.2', u'1.7.2-Forge10.12.0.1015', u'1.7.2-Forge10.12.2.1147', u'1.7.2-LiteLoader1.7.2', u'1.7.2-OptiFine_HD_U_D4', u'1.8', u'1.8-Forge11.14.1.1334']
[WARNING][mcedit2.editorapp:90]:UserFilesDirectory: C:\Users\Cas\Desktop\MCEDIT~1.0AL\MCEdit User Data
[INFO][mcedit2.editorapp:98]:Loaded translator.
[INFO][mcedit2.editorapp:107]:Loaded stylesheet.
[INFO][mcedit2.editorapp:119]:Loaded main window.
[INFO][mcedit2.editorapp:159]:Loaded panels.
[INFO][mcedit2.editorapp:202]:Loaded debug widgets.
[INFO][mcedit2.editorapp:253]:Loaded menus.
[INFO][mcedit2.worldlist:134]:Size hint: PySide.QtCore.QSize(120, 73)
[INFO][mcedit2.worldlist:135]:Size : PySide.QtCore.QSize(120, 100)
[INFO][mcedit2.worldlist:331]:Scanning C:\Users\Cas\AppData\Roaming\.minecraft\saves for worlds...
[INFO][mceditlib.anvil.adapter:511]:Adding block IDs from FML for MC 1.7
[INFO][mceditlib.anvil.adapter:557]:Added 0 blocks.
[INFO][mceditlib.anvil.adapter:511]:Adding block IDs from FML for MC 1.7
[INFO][mceditlib.anvil.adapter:557]:Added 0 blocks.
[INFO][mcedit2.util.minecraftinstall:257]:Created ResourceLoader with search path:
C:\Users\Cas\AppData\Roaming\.minecraft\versions\1.7.2\1.7.2.jar (7a304554fdea879a799efe6eaedd8c95),
C:\Users\Cas\AppData\Roaming\.minecraft\versions\1.8\1.8.jar (8663a10cecc10eaa683a927ef5371852)
[INFO][mcedit2.worldlist:371]:Loading block models...
[INFO][mcedit2.worldlist:371]:Loading block models 0/1391
[INFO][mcedit2.worldlist:371]:Loading block models 100/1391
[INFO][mcedit2.worldlist:371]:Loading block models 200/1391
[INFO][mcedit2.worldlist:371]:Loading block models 300/1391
[INFO][mcedit2.worldlist:371]:Loading block models 400/1391
[INFO][mcedit2.worldlist:371]:Loading block models 500/1391
[INFO][mcedit2.worldlist:371]:Loading block models 600/1391
[INFO][mcedit2.worldlist:371]:Loading block models 700/1391
[INFO][mcedit2.worldlist:371]:Loading block models 800/1391
[INFO][mcedit2.worldlist:371]:Loading block models 900/1391
[INFO][mcedit2.worldlist:371]:Loading block models 1000/1391
[INFO][mcedit2.worldlist:371]:Loading block models 1100/1391
[INFO][mcedit2.worldlist:371]:Loading block models 1200/1391
[INFO][mcedit2.worldlist:371]:Loading block models 1300/1391
[INFO][mcedit2.rendering.textureatlas:111]:Preloaded 349 textures for world Keralis Pretty Flat World 2 (471 kB)
[INFO][mcedit2.util.qglcontext:21]:OpenGL Version Info:
[INFO][mcedit2.util.qglcontext:36]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_1_1
[INFO][mcedit2.util.qglcontext:36]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_1_2
[INFO][mcedit2.util.qglcontext:36]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_1_3
[INFO][mcedit2.util.qglcontext:36]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_1_4
[INFO][mcedit2.util.qglcontext:36]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_1_5
[INFO][mcedit2.util.qglcontext:36]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_2_0
[INFO][mcedit2.util.qglcontext:36]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_3_0
[INFO][mcedit2.util.qglcontext:36]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_3_1
[INFO][mcedit2.util.qglcontext:63]:Obtained a GL context with this format:
Valid: True
Version: 3.1
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True

Driver info:
GL_VERSION: 3.1.0 - Build 9.17.10.2932 (3, 1)
GL_VENDOR: Intel
GL_RENDERER: Intel(R) HD Graphics 3000

[INFO][mcedit2.worldview.worldview:781]:LAYER Blocks VISIBLE True
[INFO][mcedit2.worldview.worldview:781]:LAYER Entities VISIBLE True
[INFO][mcedit2.worldview.worldview:781]:LAYER Items VISIBLE True
[INFO][mcedit2.worldview.worldview:781]:LAYER TileEntities VISIBLE True
[INFO][mcedit2.worldview.worldview:781]:LAYER TileTicks VISIBLE True
[INFO][mcedit2.rendering.textureatlas:205]:Terrain atlas created for world Keralis Pretty Flat World 2 (471/505 kB)
[INFO][mcedit2.rendering.textureatlas:206]:Cooking quads for 1238 models...
[INFO][mcedit2.worldview.worldview:149]:Changing MinimapWorldView(u'None') to dimension WorldEditorDimension(dimName='', adapter=AnvilWorldAdapter(u'C:\\Users\\Cas\\AppData\\Roaming\\.minecraft\\saves\\Keralis Pretty Flat World 2'))
[INFO][mcedit2.rendering.chunkloader:140]:Added: client MinimapWorldView(u'Keralis Pretty Flat World 2: ')
[INFO][mcedit2.worldlist:391]:Centering on single-player player.
[INFO][mcedit2.worldlist:410]:Switched world view
[INFO][mcedit2.editorapp:263]:Loaded world list.
[INFO][mcedit2.editorapp:282]:Loaded status bar.
[INFO][mcedit2.editorapp:564]:Updating recent files menu: (0) []
[INFO][mcedit2.editorapp:289]:Loaded settings.
[WARNING][mcedit2.widgets.configureblocksdialog:119]:Failed to read definitions file defined_blocks.json
[INFO][mcedit2.editorapp:310]:Loaded app dialogs.
[INFO][mcedit2.editorapp:318]:Loading timer started
[INFO][mcedit2.editorapp:328]:Finding plugins
[INFO][mcedit2.plugins:199]:Loading plugins from C:\Users\Cas\Desktop\MCEDIT~1.0AL\MCEdit User Data\plugins
[INFO][mcedit2.plugins:111]:Trying to load plugin from koch.py
[INFO][mcedit2.plugins:122]:Loaded koch.py (Koch Snowflake)
[INFO][mcedit2.plugins:111]:Trying to load plugin from storagedrawers.py
[INFO][mcedit2.plugins:122]:Loaded storagedrawers.py (storagedrawers)
[INFO][mcedit2.plugins:111]:Trying to load plugin from city.py
[INFO][mcedit2.plugins:122]:Loaded city.py (GFX: City)
[INFO][mcedit2.editorapp:344]:Opening worlds from command line.
[INFO][mceditlib.worldeditor:414]:Scanning for regions in C:\Users\Cas\AppData\Roaming\.minecraft\saves\Keralis Pretty Flat World 2...
[INFO][mceditlib.worldeditor:423]:Dim : Found 9889 chunks in 0.27 seconds.
[INFO][mceditlib.worldeditor:423]:Dim DIM1: Found 40 chunks in 0.02 seconds.
[INFO][mceditlib.worldeditor:423]:Dim DIM-1: Found 41 chunks in 0.02 seconds.
[INFO][mcedit2.worldlist:423]:Removing view from WorldListWidget
[INFO][mceditlib.anvil.adapter:511]:Adding block IDs from FML for MC 1.7
[INFO][mceditlib.anvil.adapter:557]:Added 0 blocks.
[INFO][mcedit2.util.minecraftinstall:257]:Created ResourceLoader with search path:
C:\Users\Cas\AppData\Roaming\.minecraft\versions\1.7.2\1.7.2.jar (7a304554fdea879a799efe6eaedd8c95),
C:\Users\Cas\AppData\Roaming\.minecraft\versions\1.8\1.8.jar (8663a10cecc10eaa683a927ef5371852)
[INFO][mcedit2.worldlist:371]:Loading block models...
[INFO][mcedit2.worldlist:371]:Loading block models 0/1391
[INFO][mcedit2.worldlist:371]:Loading block models 100/1391
[INFO][mcedit2.worldlist:371]:Loading block models 200/1391
[INFO][mcedit2.worldlist:371]:Loading block models 300/1391
[INFO][mcedit2.worldlist:371]:Loading block models 400/1391
[INFO][mcedit2.worldlist:371]:Loading block models 500/1391
[INFO][mcedit2.worldlist:371]:Loading block models 600/1391
[INFO][mcedit2.worldlist:371]:Loading block models 700/1391
[INFO][mcedit2.worldlist:371]:Loading block models 800/1391
[INFO][mcedit2.worldlist:371]:Loading block models 900/1391
[INFO][mcedit2.worldlist:371]:Loading block models 1000/1391
[INFO][mcedit2.worldlist:371]:Loading block models 1100/1391
[INFO][mcedit2.worldlist:371]:Loading block models 1200/1391
[INFO][mcedit2.worldlist:371]:Loading block models 1300/1391
[INFO][mcedit2.rendering.textureatlas:111]:Preloaded 349 textures for world Keralis Pretty Flat World 2 (471 kB)
[INFO][mcedit2.util.qglcontext:21]:OpenGL Version Info:
[INFO][mcedit2.util.qglcontext:36]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_1_1
[INFO][mcedit2.util.qglcontext:36]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_1_2
[INFO][mcedit2.util.qglcontext:36]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_1_3
[INFO][mcedit2.util.qglcontext:36]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_1_4
[INFO][mcedit2.util.qglcontext:36]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_1_5
[INFO][mcedit2.util.qglcontext:36]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_2_0
[INFO][mcedit2.util.qglcontext:36]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_3_0
[INFO][mcedit2.util.qglcontext:36]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_3_1
[INFO][mcedit2.util.qglcontext:63]:Obtained a GL context with this format:
Valid: True
Version: 3.1
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True

Driver info:
GL_VERSION: 3.1.0 - Build 9.17.10.2932 (3, 1)
GL_VENDOR: Intel
GL_RENDERER: Intel(R) HD Graphics 3000

[INFO][mcedit2.worldview.worldview:781]:LAYER Blocks VISIBLE True
[INFO][mcedit2.worldview.worldview:781]:LAYER Entities VISIBLE True
[INFO][mcedit2.worldview.worldview:781]:LAYER Items VISIBLE True
[INFO][mcedit2.worldview.worldview:781]:LAYER TileEntities VISIBLE True
[INFO][mcedit2.worldview.worldview:781]:LAYER TileTicks VISIBLE True
[INFO][mcedit2.rendering.textureatlas:205]:Terrain atlas created for world Keralis Pretty Flat World 2 (471/505 kB)
[INFO][mcedit2.rendering.textureatlas:206]:Cooking quads for 1238 models...
[INFO][mcedit2.worldview.worldview:149]:Changing MinimapWorldView(u'None') to dimension WorldEditorDimension(dimName='', adapter=AnvilWorldAdapter(u'C:\\Users\\Cas\\AppData\\Roaming\\.minecraft\\saves\\Keralis Pretty Flat World 2'))
[INFO][mcedit2.rendering.chunkloader:140]:Added: client MinimapWorldView(u'Keralis Pretty Flat World 2: ')
[INFO][mcedit2.worldlist:391]:Centering on single-player player.
[INFO][mcedit2.worldlist:410]:Switched world view
[INFO][mcedit2.rendering.loadablechunks:90]:Making checkerboard texture...
[INFO][mceditlib.worldeditor:414]:Scanning for regions in C:\Users\Cas\AppData\Roaming\.minecraft\saves\Keralis Pretty Flat World 2...
[INFO][mceditlib.worldeditor:423]:Dim : Found 9889 chunks in 0.34 seconds.
[INFO][mceditlib.worldeditor:423]:Dim DIM1: Found 40 chunks in 0.03 seconds.
[INFO][mceditlib.worldeditor:423]:Dim DIM-1: Found 41 chunks in 0.03 seconds.
[ERROR][<string>:153]:Unhandled Exception: 
	Attempt to call an undefined function glActiveTexture, check for bool(glActiveTexture) before calling
Traceback (most recent call last):
  File "out00-PYZ.pyz\mcedit2.worldview.worldview", line 493, in paintGL (self is a MinimapWorldView)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 393, in renderScene  
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a MatrixRenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a DepthOffsetRenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 93, in compile (self is a TextureAtlasRenderNode)
  File "out00-PYZ.pyz\mcedit2.util.glutils", line 149, in compile (self is a DisplayList)
  File "out00-PYZ.pyz\mcedit2.util.glutils", line 162, in _compile (self is a DisplayList)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 122, in draw (self is a TextureAtlasRenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 143, in enter (self is a TextureAtlasRenderNode)
  File "out00-PYZ.pyz\OpenGL.platform.baseplatform", line 407, in __call__  
NullFunctionError: Attempt to call an undefined function glActiveTexture, check for bool(glActiveTexture) before calling
[ERROR][<string>:153]:Unhandled Exception: 
	exception: access violation reading 0x000000001A186614
Traceback (most recent call last):
  File "out00-PYZ.pyz\mcedit2.worldview.worldview", line 493, in paintGL (self is a MinimapWorldView)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 393, in renderScene  
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a MatrixRenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a DepthOffsetRenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a TextureAtlasRenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderstateLowDetailNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a TranslateRenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 93, in compile (self is a VertexRenderNode)
  File "out00-PYZ.pyz\mcedit2.util.glutils", line 149, in compile (self is a DisplayList)
  File "out00-PYZ.pyz\mcedit2.util.glutils", line 162, in _compile (self is a DisplayList)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 96, in draw (self is a VertexRenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 233, in drawSelf (self is a VertexRenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 267, in drawArrays (self is a VertexRenderNode)
WindowsError: exception: access violation reading 0x000000001A186614
[ERROR][<string>:153]:Unhandled Exception: 
	exception: access violation reading 0xFFFFFFFFFFFFFFFF
Traceback (most recent call last):
  File "out00-PYZ.pyz\mcedit2.worldview.worldview", line 493, in paintGL (self is a MinimapWorldView)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 393, in renderScene  
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a MatrixRenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a DepthOffsetRenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a TextureAtlasRenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderstateLowDetailNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a TranslateRenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 93, in compile (self is a VertexRenderNode)
  File "out00-PYZ.pyz\mcedit2.util.glutils", line 149, in compile (self is a DisplayList)
  File "out00-PYZ.pyz\mcedit2.util.glutils", line 162, in _compile (self is a DisplayList)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 96, in draw (self is a VertexRenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 233, in drawSelf (self is a VertexRenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 267, in drawArrays (self is a VertexRenderNode)
WindowsError: exception: access violation reading 0xFFFFFFFFFFFFFFFF
[ERROR][<string>:153]:Unhandled Exception: 
	exception: access violation reading 0xFFFFFFFFFFFFFFFF
Traceback (most recent call last):
  File "out00-PYZ.pyz\mcedit2.worldview.worldview", line 493, in paintGL (self is a MinimapWorldView)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 393, in renderScene  
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a MatrixRenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a DepthOffsetRenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a TextureAtlasRenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderstateLowDetailNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a TranslateRenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 93, in compile (self is a VertexRenderNode)
  File "out00-PYZ.pyz\mcedit2.util.glutils", line 149, in compile (self is a DisplayList)
  File "out00-PYZ.pyz\mcedit2.util.glutils", line 162, in _compile (self is a DisplayList)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 96, in draw (self is a VertexRenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 233, in drawSelf (self is a VertexRenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 267, in drawArrays (self is a VertexRenderNode)
WindowsError: exception: access violation reading 0xFFFFFFFFFFFFFFFF
[ERROR][<string>:153]:Unhandled Exception: 
	exception: access violation reading 0xFFFFFFFFFFFFFFFF
Traceback (most recent call last):
  File "out00-PYZ.pyz\mcedit2.worldview.worldview", line 493, in paintGL (self is a MinimapWorldView)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 393, in renderScene  
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a MatrixRenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a DepthOffsetRenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a TextureAtlasRenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderstateLowDetailNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a TranslateRenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 93, in compile (self is a VertexRenderNode)
  File "out00-PYZ.pyz\mcedit2.util.glutils", line 149, in compile (self is a DisplayList)
  File "out00-PYZ.pyz\mcedit2.util.glutils", line 162, in _compile (self is a DisplayList)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 96, in draw (self is a VertexRenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 233, in drawSelf (self is a VertexRenderNode)
  File "out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 267, in drawArrays (self is a VertexRenderNode)
WindowsError: exception: access violation reading 0xFFFFFFFFFFFFFFFF

i have no idea what to do ore whats the problem, ive tried other versions, same problem.

**Comment by codewarrior0** [comment] 2015-06-19 17:25
Does the same thing happen with build 472?

**Comment by supercas240** [comment] 2015-06-20 07:14
yes it does

**Comment by supercas240** [comment] 2015-06-20 07:17
yes it does and other versions aswell

**Comment by codewarrior0** [comment] 2015-06-20 08:29
Duplicate of #110.

It would help me if you could post your log file from build 472.

**Closed by codewarrior0** 2015-06-20 08:29 UTC

**Comment by supercas240** [comment] 2015-06-20 09:07
where do i find th log file

**Comment by supercas240** [comment] 2015-06-20 09:24
i do have an intel HD grapics 3000
