### ISSUE TITLE
Error 0x0000000000000000 ver.370 x64

### ISSUE THREAD

**Issue by cbprog** [mcedit/mcedit2#95] opened 2015-05-19 11:19 UTC
![GitHub Logo](http://www.cb.16mb.com/temp/mcedit.jpg)

**Comment by Rubisk** [comment] 2015-05-19 12:24
duplicate of #78?

**Comment by codewarrior0** [comment] 2015-05-20 02:45
Yes.

**Closed by codewarrior0** 2015-05-20 02:45 UTC

**Comment by OniOniOn-** [comment] 2015-05-20 15:44
If my pc run mcedit 2 tech. preview long time ago, would it not get this error? Or is it just a real problem in code.
