### ISSUE TITLE
MCEdit error on start.

### ISSUE THREAD

**Issue by othba** [mcedit/mcedit2#200] opened 2016-01-13 16:31 UTC
Procedure; I downloaded the unpacker and packed it up on my desktop. Then i just tried to start it and woop a error pops up. 
MCEdit ver: Alpha921 [Newest]
MC ver: I'm using 1.8.8 with no mods.
Op system: Win10 Home

Error log; MCEdit version: 2.0.0alpha-921
Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-8-6.2.9200
Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.5.13416 Compatibility Profile Context 15.300.1025.0 (4, 5)
GL_VENDOR: 'ATI Technologies Inc.'
GL_RENDERER: 'AMD Radeon (TM) R9 Fury Series'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\worldview\worldview.py", line 574, in paintGL (self is a MinimapWorldView)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 259, in renderScene  
  File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 94, in compile (self is a VertexRenderNode)
  File "mcedit2\util\glutils.py", line 145, in compile (self is a DisplayList)
  File "mcedit2\util\glutils.py", line 150, in _compile (self is a DisplayList)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 108, in draw (self is a VertexRenderNode)
  File "mcedit2\rendering\scenegraph\vertex_array.py", line 47, in drawSelf (self is a VertexRenderNode)
  File "mcedit2\rendering\scenegraph\vertex_array.py", line 81, in drawArrays (self is a VertexRenderNode)
WindowsError: exception: access violation reading 0x0000000000000000

**Comment by GrayTap** [comment] 2016-01-13 18:41
Same thing for me, The last few builds have been the same. I haven't found a build that loads yet.

MCEdit version: 2.0.0alpha-921
Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-8-6.2.9200
Processor: AMD64 Family 15 Model 107 Stepping 2, AuthenticAMD

Obtained a GL context with this format:
Valid: True
Version: 3.3
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 3.3.11672 Compatibility Profile Context (3, 3)
GL_VENDOR: 'ATI Technologies Inc.'
GL_RENDERER: 'ATI Radeon HD 3200 Graphics'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\worldview\worldview.py", line 574, in paintGL (self is a MinimapWorldView)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 259, in renderScene  
  File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 94, in compile (self is a VertexRenderNode)
  File "mcedit2\util\glutils.py", line 145, in compile (self is a DisplayList)
  File "mcedit2\util\glutils.py", line 150, in _compile (self is a DisplayList)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 108, in draw (self is a VertexRenderNode)
  File "mcedit2\rendering\scenegraph\vertex_array.py", line 47, in drawSelf (self is a VertexRenderNode)
  File "mcedit2\rendering\scenegraph\vertex_array.py", line 81, in drawArrays (self is a VertexRenderNode)
WindowsError: exception: access violation reading 0x0000000000000000

**Comment by codewarrior0** [comment] 2016-01-15 08:43
Duplicate of #110

**Closed by codewarrior0** 2016-01-15 08:43 UTC
