### ISSUE TITLE
Cast array data error when trying to Fill blocks

### ISSUE THREAD

**Issue by siapelan** [mcedit/mcedit2#102] opened 2015-05-24 16:44 UTC
I have Selected a part of a world (typically 10x10x10 block size) and tried to Fill with Stone (Edit - Fill), but get the error message in the attached picture. What is the problem?
![error](https://cloud.githubusercontent.com/assets/12586210/7788673/d1a60c3a-0244-11e5-8f70-a63182a7a0f2.jpg)

**Comment by codewarrior0** [comment] 2015-05-24 16:53
Duplicate of #74

**Closed by codewarrior0** 2015-05-24 16:53 UTC
