### ISSUE TITLE
Unhandled exception : list of index out of range 

### ISSUE THREAD

**Issue by sadeksadek** [mcedit/mcedit2#87] opened 2015-05-13 17:44 UTC
everytime i open the launcher it goes : Unhandled exception : list of index out of range

**Comment by Rubisk** [comment] 2015-05-13 18:20
Could you please give a full traceback etc?

Some more info on what is needed to fix a bug: https://github.com/mcedit/mcedit2/blob/master/CONTRIBUTING.md

**Comment by ramziC** [comment] 2015-05-15 13:57
This is same thing i have when I try to edit world.

- I can start MCedit 2 normal , I can select worlds and it loads chunks normal but once i press Edit button it starts to load world and stops every time at 50% ( loading tools... ) and window shows up " An error has occured.  Unhandled exception : list of index out of range " 

- Version : mcedit2-win32-2.0.0alpha-328 ( tried older version and same bug )

- Minecraft version : 1.8.4 ( but it bugs on any version ) , and no mods 

- Operating System Version : Win 7 64 bit


Here is error.log :  http://pastebin.com/mzhCV9Up

**Comment by codewarrior0** [comment] 2015-05-15 13:58
Duplicate of #88, already fixed.

**Closed by codewarrior0** 2015-05-15 13:58 UTC
Labels: didn't read the guidelines
