### ISSUE TITLE
Newest Load doesnt work.

### ISSUE THREAD

**Issue by Rhoues** [mcedit/mcedit2#201] opened 2016-01-13 21:03 UTC
I just downloaded mcedit2-win64-2.0.0alpha-921 After spending much time trying to get previous versions to work (to no avail). I have tried everything from running as admin, to compatibility issues, to different versions. Latest version doesnt produce an error message. Everything loads then just pops up as "MCEdit has stopped working. Close program." the back menus do open like its about to work then bam. Freezes. Other versions all have unexpected errors. I have noticed though, that when I download the "installer" and it extracts, when you start mcedit and it makes the User Data folder, it puts "plugins" in the User data folder when the olther folder is where it needs to be.

Any ideas on a fix or is this happening to anyone else?

Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz 8 GB Ram 64 bit OS
Tried Versions:Alpha 918 to 921.
MCEdit version 1 works, its just not very friendly as the newer one was.

**Comment by codewarrior0** [comment] 2016-01-15 08:46
Probably a duplicate of #110. The Event Viewer program should have an entry for the crash that gives more details about it.

**Comment by codewarrior0** [comment] 2016-01-31 01:37
Could you try build 932 and tell me if it still happens?

**Closed** 2016-03-27 14:07 UTC
Labels: duplicate
