### ISSUE TITLE
Attempt to call an undefined function glActiveTexture on 32-bit-windows

### ISSUE THREAD

**Issue by Rubisk** [mcedit/mcedit2#78] opened 2015-05-09 10:00 UTC
Note: I had to build all the .pyx files manually, by going into a python console and doing:
from Cython.Build import cythonize
cythonize('src/mceditlib/nbt.pyx')
cythonize(["src/mcedit2/rendering/blockmodels.pyx","src/mcedit2/rendering/modelmesh.pyx",])

After that, I was able to run setup.py develop without problems, but starting mcedit throws this error:
http://pastebin.com/mcDK8fWp

**Comment by codewarrior0** [comment] 2015-05-09 10:21
`setup.py develop` is meant to run cythonize, compile to .pyd and put the modules in your pythonpath. If that didn't work, you should post the output of `setup.py develop` on a clean checkout instead of doing whatever this is. It obviously didn't build those modules correctly.

**Comment by codewarrior0** [comment] 2015-05-09 10:41
I take that back, the cython modules aren't mentioned in the error.

Still, it looks like a problem with your checkout - ChunkMeshBase is actually in that file - so please try again with a clean checkout.

**Comment by Rubisk** [comment] 2015-05-09 10:42
Sure.... I recloned the repo to remove my self-builded nbt.pyd and nbt.c ,blockmodels.pyd, blockmodels.c etc.

http://pastebin.com/qwSavH2A

**Comment by codewarrior0** [comment] 2015-05-09 11:03
It looks like the cythonize call in setup.py isn't doing anything. I don't know why.

Try running `setup.py build_ext --inplace` and see if that runs cythonize. The first two lines of output should be

```
Compiling src/mceditlib/nbt.pyx because it changed.
Cythonizing src/mceditlib/nbt.pyx
```

**Comment by Rubisk** [comment] 2015-05-09 11:07
Gives same error. That's why I manually ran those cythonize calls at first, I guess that's bound to fail?

**Comment by codewarrior0** [comment] 2015-05-09 11:16
Maybe you're on an old version of Cython? I'm on 0.22. 

Oh well. Rebuild the `.pyd`s somehow and try `mcedit2` again, see if it gives the same error. You should also have a `cythonize` script that you can run from the command prompt without going into python.

The original error you posted makes no sense. It says it can't find `mcedit2.rendering.blockmeshes.ChunkMeshBase` on line 9, but on the line right before that it imported `mcedit2.rendering.blockmeshes.standardCubeTemplates` from the same file!

**Comment by Rubisk** [comment] 2015-05-09 11:21
Hmm weird... I reinstalled Cython without any errors, but then it still didn't compile.

I changed setup.py to take the setuptools from distutils.core, then it DID build the .pyd files, but crashed on trying to actually use them, probably wasn't the way to go either.

I'll rebuild using the old way that worked and see if anything changed.

**Comment by codewarrior0** [comment] 2015-05-09 11:23
Also, I recommend using a virtualenv as described in the README, to isolate your mcedit2 dev environment from your system-wide python. When using the windows command prompt, you'll have to run `ENV\scripts\activate.bat` instead of `. ENV/scripts/activate`

> I changed setup.py to take the setuptools from distutils.core

I bet your setuptools is out of date. Try running `pip install -U setuptools`

**Comment by Rubisk** [comment] 2015-05-09 11:27
Updating setuptools did something, it now crashes somewhere further:

http://pastebin.com/gRh0i0qN

**Comment by codewarrior0** [comment] 2015-05-09 11:34
Oh, whoops! I'm actually using cython 0.21.2, my bad. That looks like a bug in cython related to using memoryviews with profiling enabled. Install that version of cython with `pip install cython==0.21.2` and try again.

**Comment by codewarrior0** [comment] 2015-05-09 12:02
I... guess I [reported the problem to the cython guys.](https://github.com/cython/cython/commit/b42e181f0c3bd9e714245de11c692f6bbe48571b#commitcomment-11119128)

**Comment by Rubisk** [comment] 2015-05-09 12:11
Thanks for the help! I'm setting up a virtualenv right now (numpy is taking FOREVER to install, been going for 15 minutes or so now, I'll let you know if it works)

**Comment by codewarrior0** [comment] 2015-05-09 12:17
This might help you save some time. The link is buried way down in the readme. This is all of the modules I'm using to develop on win32 and win-x64, some of which I built myself. You'll have to use `easy_install` to install the exes into a virtualenv.

https://www.dropbox.com/sh/fw8u5f050r1m6lp/AABAYXOEAzmV_nfH0Qj9hUOwa?dl=0

**Comment by Rubisk** [comment] 2015-05-09 12:36
Well.... http://pastebin.com/gUK1aTEB :-(

I got everything setup, think this is caused by an outdated opengl. My graphics card is the Nvidia geforce G210 (yay :/), and Ive got opengl 3.1.0 in my virtual environment right now.

**Comment by codewarrior0** [comment] 2015-05-09 12:40
I remember fixing a bug in PyOpenGL that only happened on 64 bit systems with certain drivers. This might be similar.

Could you try both of tonight's builds and tell me if there's any difference between 32 and 64 bit? http://www.mcedit.net/downloads.html

**Comment by Rubisk** [comment] 2015-05-09 12:42
latest is 19 days old?

**Comment by codewarrior0** [comment] 2015-05-09 12:42
There should be one from a few hours ago.

**Comment by Rubisk** [comment] 2015-05-09 12:47
Wow. My browser cached that thing for a long amount of time, huh. No difference in terms of crashes on startup... Not sure what to look for.

**Comment by codewarrior0** [comment] 2015-05-09 12:59
There's a couple of things I need to do then. The easy part is to update the readme with notes about the setuptools and cython versions, and possibly find a workaround for cython 0.22 regarding the profiling+memoryviews+MSVC problem. Maybe just disable profiling for that file and only turn it on locally when it's needed.

The less easy part is to add a bunch of code to explicitly create the GL context, check that it's at least OpenGL 1.3 for the multitextures and hardware-accelerated, and spit out a bunch of debug info about the GL drivers and all that so we can maybe find a cure. Or at least run in GL1.1 mode somehow, but I bet that would be pretty dumb if it's just getting a software renderer.

**Comment by Rubisk** [comment] 2015-05-09 13:09
Isn't it this just a duplicate of #16 then?

**Comment by codewarrior0** [comment] 2015-05-09 22:40
It could be similar, but here's what I think is the difference. 

`Attempt to call an undefined function glActiveTexture` says that the OpenGL context doesn't have the GL version 1.3 required for glActiveTexture. `error: access violation` while calling glActiveTexture says the GL version was correct, but there was a problem getting the function pointer for glActiveTexture (via wglGetProcAddress) either in PyOpenGL or in the GL driver provided by the GPU vendor.

Huh. We never did figure out what exactly caused the "Can't import ChunkMeshBase" to begin with, did we? It just went away after you got everything into a virtualenv.

**Comment by Rubisk** [comment] 2015-05-10 09:34
We never did. It just disappeared, no idea what caused it.

Did some googling on the glActiveTexture error, can't find much. I did find an old pyOpenGl issue you fixed:
http://sourceforge.net/p/pyopengl/mailman/message/30720512/ 
But not much else. I just realized I'm on python 32 bit, I'll try get a 64 bit going and see how that works?

**Comment by Rubisk** [comment] 2015-05-10 10:14
That did it. I can run from source now :-) OpenGL-accelerate doesn't seem to be working, I get a bunch of warning in the console from it, but at least it works. I'll leave this issue open in case you still want to look at the glActiveTexture error. Thanks a lot for your support :D

**Comment by xShevy** [comment] 2015-05-15 00:25
which is the ultimate solution for 32-bit? (google translator xD)

**Comment by codewarrior0** [comment] 2015-05-24 14:55
I've added some code to validate the OpenGL version and require hardware rendering. It will be appearing in the next build later today.

@Rubisk, since you can reproduce this on a source checkout, it would be appreciated if you could gather some info and play around with it a bit. The relevant file is `src/mcedit2/util/qglcontext.py`.

**Comment by Rubisk** [comment] 2015-05-24 15:28
Probably would have to get a 32 bit python running again then. guess I need that to compule the mcpe wrapper anyway. Ill test  it for you i  a few days, currently broke my 32 python.

**Comment by Rubisk** [comment] 2015-05-25 09:01
Welp got a 32-bit going, but can't reproduce the issue anymore. I don't know a thing about OpenGL, I'd say you fixed it, but I don't know for sure.

**Comment by codewarrior0** [comment] 2015-06-02 02:10
Tentatively closing this one as fixed. If it comes up again, we can open a new issue - this one got way off topic.

**Closed by codewarrior0** 2015-06-02 02:10 UTC
Labels: bug

**Comment by AlphaPlex** [comment] 2015-12-25 03:56
I have the same error when i try to open MCEdit 64 bit and from what you guys posted, I can't understand a word. Can someone explain how to fix?

**Comment by AlphaPlex** [comment] 2015-12-25 03:56
I also tried 32 bit, the same problem emerged
