### ISSUE TITLE
unvailed win exe

### ISSUE THREAD

**Issue by mcpebro** [mcedit/mcedit2#109] opened 2015-06-05 16:39 UTC
it does not work it says its invailed

**Comment by mcpebro** [comment] 2015-06-05 16:45
i got it working now [INFO][<string>:131]:MCEdit2 version 2.0.0alpha-435 starting...
[INFO][mcedit2.util.profiler:87]:Decorating <function work at 0x02DF01B0> with work
[INFO][OpenGL.acceleratesupport:13]:OpenGL_accelerate module loaded
[INFO][OpenGL.arrays.arraydatatype:270]:Using accelerated ArrayDatatype
[INFO][mcedit2.util.profiler:87]:Decorating <function loadSections at 0x03412670> with SelectionScene
[INFO][mcedit2.util.profiler:87]:Decorating <function __iter__ at 0x0345A470> with ChunkUpdate
[INFO][mcedit2.util.profiler:87]:Decorating <function buildChunkMeshes at 0x0345A430> with buildChunkMeshes
[INFO][mcedit2.util.profiler:87]:Decorating <function buildSectionMeshes at 0x0345A4F0> with buildSectionMeshes
[INFO][mcedit2.util.profiler:87]:Decorating <function __iter__ at 0x0345AD30> with SectionUpdate
[INFO][mcedit2.util.settings:100]:Loading app settings from C:\DOCUME~1\owner\Desktop\mcedit\MCEDIT~2.0AL\MCEdit User Data\mcedit2.ini
[INFO][mcedit2.util.profiler:87]:Decorating <function workOnChunk at 0x037313F0> with SlicedMesh
[ERROR][<string>:153]:Unhandled Exception: 
	[Error 127] The specified procedure could not be found
Traceback (most recent call last):
  File "<string>", line 171, in <module>  
  File "<string>", line 167, in main  
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\mcedit2.util.profiler", line 65, in _wrapper (self is a Profiler)
  File "<string>", line 142, in startup  
  File "c:\users\rio\documents\src\pyinstaller\PyInstaller\loader\pyi_importers.py", line 276, in load_module (self is a FrozenImporter)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\mcedit2.editorapp", line 33, in <module>  
  File "c:\users\rio\documents\src\pyinstaller\PyInstaller\loader\pyi_importers.py", line 276, in load_module (self is a FrozenImporter)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\mcedit2.util.ipython_widget", line 67, in <module>  
  File "c:\users\rio\documents\src\pyinstaller\PyInstaller\loader\pyi_importers.py", line 276, in load_module (self is a FrozenImporter)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\IPython.qt.inprocess", line 5, in <module>  
  File "c:\users\rio\documents\src\pyinstaller\PyInstaller\loader\pyi_importers.py", line 276, in load_module (self is a FrozenImporter)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\IPython.kernel", line 4, in <module>  
  File "c:\users\rio\documents\src\pyinstaller\PyInstaller\loader\pyi_importers.py", line 276, in load_module (self is a FrozenImporter)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\IPython.kernel.zmq", line 14, in <module>  
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\IPython.utils.zmqrelated", line 35, in check_for_zmq  
  File "c:\users\rio\documents\src\pyinstaller\PyInstaller\loader\pyi_importers.py", line 276, in load_module (self is a FrozenImporter)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\zmq", line 30, in <module>  
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\ctypes", line 443, in LoadLibrary (self is a LibraryLoader)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\ctypes", line 365, in __init__ (self is a CDLL)
WindowsError: [Error 127] The specified procedure could not be found

**Comment by codewarrior0** [comment] 2015-06-06 01:22
Possible duplicate of #107. What version of Windows do you have?

**Comment by mcpebro** [comment] 2015-06-18 15:43
i dont know

**Closed** 2015-07-06 13:57 UTC
Labels: bug
