### ISSUE TITLE
Same issue that was deemed as fixed is not.

### ISSUE THREAD

**Issue by hoodhoodihopman** [mcedit/mcedit2#341] opened 2017-07-03 15:30 UTC
An error occurred while opening C:/Users/Kevin/Desktop/HaljalikaServer (Hal)-2/level.dat
Failed to read PNG file C:\Users\Kevin\Desktop\mcedit2-win64-2.0.0-beta9\MCEdit 2 Files\player_data\skins\0701fdfbd8b94ac98c01657868121ec4.png

Traceback (most recent call last):
  File "mcedit2\editorapp.py", line 781, in loadFile (self is a MCEditApp)
  File "mcedit2\editorsession.py", line 515, in __init__ (self is a EditorSession)
  File "mcedit2\editorsession.py", line 1442, in __init__ (self is a EditorTab)
  File "mcedit2\worldview\minimap.py", line 152, in __init__ (self is a MinimapWorldView)
  File "mcedit2\worldview\worldview.py", line 192, in __init__ (self is a MinimapWorldView)
  File "mcedit2\worldview\worldview.py", line 233, in setDimension (self is a MinimapWorldView)
  File "mcedit2\worldview\worldview.py", line 259, in createSceneGraph (self is a MinimapWorldView)
  File "mcedit2\worldview\minimap.py", line 161, in createWorldScene (self is a MinimapWorldView)
  File "mcedit2\worldview\worldview.py", line 255, in createWorldScene (self is a MinimapWorldView)
  File "mcedit2\rendering\worldscene.py", line 235, in __init__ (self is a WorldScene)(named None)
  File "mcedit2\rendering\players.py", line 141, in __init__ (self is a PlayersNode)(named None)
  File "mcedit2\rendering\players.py", line 37, in __init__ (self is a PlayerNode)(named None)
  File "mcedit2\util\player_server.py", line 153, in getPlayerInfo  
  File "mcedit2\util\player_server.py", line 190, in _getPlayerInfo (self is a PlayerDataCache)
  File "mcedit2\rendering\players.py", line 31, in _callback (self is a PlayerNode)(named None)
  File "mcedit2\rendering\players.py", line 50, in texturePath (self is a PlayerNode)(named None)
  File "mcedit2\util\load_png.py", line 49, in loadPNGFile  
IOError: Failed to read PNG file C:\Users\Kevin\Desktop\mcedit2-win64-2.0.0-beta9\MCEdit 2 Files\player_data\skins\0701fdfbd8b94ac98c01657868121ec4.png

Windows 8 64-bit.
I'm just trying to open a world.
Plus I get errors when the program opens.

**Comment by codewarrior0** [comment] 2017-07-03 23:34
Duplicate of #338

**Closed by codewarrior0** 2017-07-03 23:34 UTC
