### ISSUE TITLE
Unhandled Exception (glActiveTexture)

### ISSUE THREAD

**Issue by xShevy** [mcedit/mcedit2#91] opened 2015-05-15 00:15 UTC
An error has ocurred

Unhandled Exception: attempt to call an undefined function glActiveTexture, check for bool(glActiveTexture) before calling

Technical Data:
  → Operating System: "Windows 7"
  → Version OS: "6.1"
  → Architecture OS: "x86"
  → Version of Java: "1.8.0_45"
  → Java Provider: "Oracle Corporation"
  → Architecture Java: "32"

PLEASE HELP ME :C

**Comment by codewarrior0** [comment] 2015-05-15 00:18
Duplicate of #78

**Closed by codewarrior0** 2015-05-15 00:18 UTC

**Comment by TH3REDSP1R1T** [comment] 2015-06-18 21:04
I have the same issue.

**Comment by codewarrior0** [comment] 2015-06-18 21:50
@TH3REDSP1R1T Post the mcedit.log file that's in the "MCEdit User Data" folder. Use pastebin.com or gist.github.com.

**Comment by TH3REDSP1R1T** [comment] 2015-06-18 22:16
here's the log.    https://gist.github.com./anonymous/551092a1d70fd1ebe977#file-gistfile1-txt

**Comment by codewarrior0** [comment] 2015-06-18 22:24
Thanks.

**Comment by Lorenzo77** [comment] 2015-07-20 08:58
got the same error .. i try some old mcedit2 version and the last (564)
os : XP sp3
java : 1.8.0_40-b25
http://pastebin.com/GJ7WhgCi
