### ISSUE TITLE
MCEDIT 2 Win64 Alphha 309 fails to start up

### ISSUE THREAD

**Issue by welchwarlock** [mcedit/mcedit2#79] opened 2015-05-09 13:01 UTC
Here is the Log. Thanks in advance for all the work you do!
WW

[INFO][mcedit2.util.settings:100]:Loading app settings from C:\McEdit\MCEdit User Data\mcedit2.ini
[INFO][OpenGL.acceleratesupport:13]:OpenGL_accelerate module loaded
[INFO][OpenGL.arrays.arraydatatype:270]:Using accelerated ArrayDatatype
[INFO][mcedit2.util.profiler:87]:Decorating <function __iter__ at 0x000000000741FC88> with ChunkUpdate
[INFO][mcedit2.util.profiler:87]:Decorating <function buildChunkMeshes at 0x000000000741FC18> with buildChunkMeshes
[INFO][mcedit2.util.profiler:87]:Decorating <function buildSectionMeshes at 0x000000000741FD68> with buildSectionMeshes
[INFO][mcedit2.util.profiler:87]:Decorating <function __iter__ at 0x0000000007428C18> with SectionUpdate
[INFO][mcedit2.util.profiler:87]:Decorating <function work at 0x0000000007437198> with work
[INFO][mcedit2.util.profiler:87]:Decorating <function loadSections at 0x00000000075BB198> with SelectionScene
[INFO][mcedit2.util.profiler:87]:Decorating <function workOnChunk at 0x00000000076A1278> with SlicedMesh
[INFO][mcedit2.util.minecraftinstall:205]:Checking install at C:\Users\My Name\AppData\Roaming\.minecraft
[INFO][mcedit2.util.minecraftinstall:212]:Found versions:
[u'1.6.1', u'1.6.2', u'1.6.4', u'1.7.2', u'1.7.4', u'1.7.9', u'1.8', u'1.8.1', u'1.8.3', u'1.8.4']
[INFO][mcedit2.util.minecraftinstall:80]:MCInstall saved settings: [{u'path': u'C:\\Users\\My Name\\AppData\\Roaming\\.minecraft', u'name': u'(Default)'}]
[WARNING][mcedit2.editorapp:84]:UserFilesDirectory: C:\McEdit\MCEdit User Data
[INFO][mcedit2.editorapp:92]:Loaded translator.
[INFO][mcedit2.editorapp:101]:Loaded stylesheet.
[INFO][mcedit2.editorapp:113]:Loaded main window.
[INFO][mcedit2.editorapp:149]:Loaded panels.
[INFO][mcedit2.editorapp:247]:Loaded menus.
[INFO][mcedit2.worldlist:134]:Size hint: PySide.QtCore.QSize(120, 73)
[INFO][mcedit2.worldlist:135]:Size : PySide.QtCore.QSize(120, 100)
[INFO][mcedit2.worldlist:324]:Scanning C:\Users\My Name\AppData\Roaming\.minecraft\saves for worlds...
[INFO][mcedit2.util.minecraftinstall:257]:Created ResourceLoader with search path:
C:\Users\My Name\AppData\Roaming\.minecraft\versions\1.6.1\1.6.1.jar (3c56fb4b77b1ca37dde69b5eb896fc4d),
C:\Users\My Name\AppData\Roaming\.minecraft\versions\1.8\1.8.jar (8663a10cecc10eaa683a927ef5371852)
[INFO][mcedit2.worldlist:364]:Loading block models...
[INFO][mcedit2.worldlist:364]:Loading block models 0/1391
[INFO][mcedit2.worldlist:364]:Loading block models 100/1391
[INFO][mcedit2.worldlist:364]:Loading block models 200/1391
[INFO][mcedit2.worldlist:364]:Loading block models 300/1391
[INFO][mcedit2.worldlist:364]:Loading block models 400/1391
[INFO][mcedit2.worldlist:364]:Loading block models 500/1391
[INFO][mcedit2.worldlist:364]:Loading block models 600/1391
[INFO][mcedit2.worldlist:364]:Loading block models 700/1391
[INFO][mcedit2.worldlist:364]:Loading block models 800/1391
[INFO][mcedit2.worldlist:364]:Loading block models 900/1391
[INFO][mcedit2.worldlist:364]:Loading block models 1000/1391
[INFO][mcedit2.worldlist:364]:Loading block models 1100/1391
[INFO][mcedit2.worldlist:364]:Loading block models 1200/1391
[INFO][mcedit2.worldlist:364]:Loading block models 1300/1391
[INFO][mcedit2.rendering.textureatlas:111]:Preloaded 349 textures for world 1_8 Test World (471 kB)
[INFO][mcedit2.worldview.worldview:775]:LAYER Blocks VISIBLE True
[INFO][mcedit2.worldview.worldview:775]:LAYER Entities VISIBLE True
[INFO][mcedit2.worldview.worldview:775]:LAYER Items VISIBLE True
[INFO][mcedit2.worldview.worldview:775]:LAYER TileEntities VISIBLE True
[INFO][mcedit2.worldview.worldview:775]:LAYER TileTicks VISIBLE True
[INFO][mcedit2.rendering.textureatlas:205]:Terrain atlas created for world 1_8 Test World (471/505 kB)
[INFO][mcedit2.rendering.textureatlas:206]:Cooking quads for 1238 models...
[INFO][mcedit2.worldview.worldview:145]:Changing MinimapWorldView(u'None') to dimension WorldEditorDimension(dimName='', adapter=AnvilWorldAdapter(u'C:\\Users\\My Name\\AppData\\Roaming\\.minecraft\\saves\\1_8 Test World'))
[INFO][mcedit2.rendering.chunkloader:121]:Added: client MinimapWorldView(u'1_8 Test World: ')
[INFO][mcedit2.worldlist:383]:Centering on single-player player.
[INFO][mcedit2.worldlist:399]:Switched world view
[INFO][mcedit2.editorapp:257]:Loaded world list.
[INFO][mcedit2.editorapp:276]:Loaded status bar.
[INFO][mcedit2.editorapp:530]:Updating recent files menu: (0) []
[INFO][mcedit2.editorapp:283]:Loaded settings.
[WARNING][mcedit2.widgets.configureblocksdialog:119]:Failed to read definitions file defined_blocks.json
[INFO][mcedit2.editorapp:300]:Loaded app dialogs.
[INFO][mcedit2.editorapp:308]:Loading timer started
[INFO][mcedit2.editorapp:319]:Opening worlds from command line.
[INFO][mceditlib.worldeditor:401]:Scanning for regions in C:\Users\My Name\AppData\Roaming\.minecraft\saves\1_8 Test World...
[INFO][mceditlib.worldeditor:411]:Dim : Found 14275 chunks in 0.28 seconds.
[INFO][mcedit2.worldlist:412]:Removing view from WorldListWidget
[INFO][mcedit2.util.minecraftinstall:257]:Created ResourceLoader with search path:
C:\Users\My Name\AppData\Roaming\.minecraft\versions\1.6.1\1.6.1.jar (3c56fb4b77b1ca37dde69b5eb896fc4d),
C:\Users\My Name\AppData\Roaming\.minecraft\versions\1.8\1.8.jar (8663a10cecc10eaa683a927ef5371852)
[INFO][mcedit2.worldlist:364]:Loading block models...
[INFO][mcedit2.worldlist:364]:Loading block models 0/1391
[INFO][mcedit2.worldlist:364]:Loading block models 100/1391
[INFO][mcedit2.worldlist:364]:Loading block models 200/1391
[INFO][mcedit2.worldlist:364]:Loading block models 300/1391
[INFO][mcedit2.worldlist:364]:Loading block models 400/1391
[INFO][mcedit2.worldlist:364]:Loading block models 500/1391
[INFO][mcedit2.worldlist:364]:Loading block models 600/1391
[INFO][mcedit2.worldlist:364]:Loading block models 700/1391
[INFO][mcedit2.worldlist:364]:Loading block models 800/1391
[INFO][mcedit2.worldlist:364]:Loading block models 900/1391
[INFO][mcedit2.worldlist:364]:Loading block models 1000/1391
[INFO][mcedit2.worldlist:364]:Loading block models 1100/1391
[INFO][mcedit2.worldlist:364]:Loading block models 1200/1391
[INFO][mcedit2.worldlist:364]:Loading block models 1300/1391
[INFO][mcedit2.rendering.textureatlas:111]:Preloaded 349 textures for world 1_8 Test World (471 kB)
[INFO][mcedit2.worldview.worldview:775]:LAYER Blocks VISIBLE True
[INFO][mcedit2.worldview.worldview:775]:LAYER Entities VISIBLE True
[INFO][mcedit2.worldview.worldview:775]:LAYER Items VISIBLE True
[INFO][mcedit2.worldview.worldview:775]:LAYER TileEntities VISIBLE True
[INFO][mcedit2.worldview.worldview:775]:LAYER TileTicks VISIBLE True
[INFO][mcedit2.rendering.textureatlas:205]:Terrain atlas created for world 1_8 Test World (471/505 kB)
[INFO][mcedit2.rendering.textureatlas:206]:Cooking quads for 1238 models...
[INFO][mcedit2.worldview.worldview:145]:Changing MinimapWorldView(u'None') to dimension WorldEditorDimension(dimName='', adapter=AnvilWorldAdapter(u'C:\\Users\\My Name\\AppData\\Roaming\\.minecraft\\saves\\1_8 Test World'))
[INFO][mcedit2.rendering.chunkloader:121]:Added: client MinimapWorldView(u'1_8 Test World: ')
[INFO][mcedit2.worldlist:383]:Centering on single-player player.
[INFO][mcedit2.worldlist:399]:Switched world view
[INFO][mcedit2.rendering.loadablechunks:90]:Making checkerboard texture...
[INFO][mceditlib.worldeditor:401]:Scanning for regions in C:\Users\My Name\AppData\Roaming\.minecraft\saves\1_8 Test World...
[INFO][mceditlib.worldeditor:411]:Dim : Found 14275 chunks in 0.37 seconds.
[ERROR][<string>:129]:Unhandled Exception: 
	Attempt to call an undefined function glActiveTexture, check for bool(glActiveTexture) before calling
Traceback (most recent call last):
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.worldview.worldview", line 491, in paintGL (self is a MinimapWorldView)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 393, in renderScene  
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a MatrixRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a DepthOffsetRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 93, in compile (self is a TextureAtlasRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.util.glutils", line 149, in compile (self is a DisplayList)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.util.glutils", line 162, in _compile (self is a DisplayList)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 122, in draw (self is a TextureAtlasRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 143, in enter (self is a TextureAtlasRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\OpenGL.platform.baseplatform", line 407, in __call__  
NullFunctionError: Attempt to call an undefined function glActiveTexture, check for bool(glActiveTexture) before calling
[ERROR][<string>:129]:Unhandled Exception: 
	exception: access violation reading 0x000000000000000C
Traceback (most recent call last):
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.worldview.worldview", line 491, in paintGL (self is a MinimapWorldView)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 393, in renderScene  
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a MatrixRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a DepthOffsetRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a TextureAtlasRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderstateLowDetailNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a TranslateRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 93, in compile (self is a VertexRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.util.glutils", line 149, in compile (self is a DisplayList)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.util.glutils", line 162, in _compile (self is a DisplayList)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 96, in draw (self is a VertexRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 233, in drawSelf (self is a VertexRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 267, in drawArrays (self is a VertexRenderNode)
WindowsError: exception: access violation reading 0x000000000000000C

**Comment by codewarrior0** [comment] 2015-05-09 13:06
Thanks. Duplicate of #16.

**Closed by codewarrior0** 2015-05-09 13:06 UTC
