### ISSUE TITLE
1.12 world does not open, gets this error message. My other worlds open but not this one.

### ISSUE THREAD

**Issue by jason-009** [mcedit/mcedit2#334] opened 2017-06-29 21:49 UTC
Click the "guidelines for contributing" link above and read it. If you do not supply the
needed information, your issue wiMCEdit version: 2.0.0-beta7
Python version: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-10-10.0.14393
Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.3
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.3.0 - Build 20.19.15.4531 (4, 3)
GL_VENDOR: 'Intel'
GL_RENDERER: 'Intel(R) HD Graphics 4600'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\panels\map.py", line 40, in data (self is a MapListModel)
  File "mcedit2\panels\map.py", line 54, in imageForMapID (self is a MapListModel)
  File "mceditlib\anvil\adapter.py", line 1129, in getColorsAsRGBA (self is a AnvilMapData)
IndexError: index 146 is out of bounds for axis 0 with size 144ll be closed without comment.

**Comment by codewarrior0** [comment] 2017-06-29 21:59
Duplicate of #328

**Closed by codewarrior0** 2017-06-29 21:59 UTC
