### ISSUE TITLE
Crash with NBT Overflow

### ISSUE THREAD

**Issue by ishitatsuyuki** [mcedit/mcedit2#142] opened 2015-07-24 00:23 UTC
So... You guys doesn't handle it?
```
[ERROR][main.py:153]:Unhandled Exception: 

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mcedit2/editorapp.py", line 733, in editWorldFromList (self is a MCEditApp)
    self.loadFile(filename)
  File "/usr/lib/python2.7/site-packages/mcedit2/editorapp.py", line 697, in loadFile (self is a MCEditApp)
    session = EditorSession(filename, resourceLoader, configuredBlocks, readonly=readonly, progressCallback=callback)
  File "/usr/lib/python2.7/site-packages/mcedit2/editorsession.py", line 319, in __init__ (self is a EditorSession)
    self.playerPanel = PlayerPanel(self)
  File "/usr/lib/python2.7/site-packages/mcedit2/panels/player.py", line 89, in __init__ (self is a PlayerPanel)
    self.setSelectedPlayerIndex(0)
  File "/usr/lib/python2.7/site-packages/mcedit2/panels/player.py", line 184, in setSelectedPlayerIndex (self is a PlayerPanel)
    self.setSelectedPlayerUUID(UUID)
  File "/usr/lib/python2.7/site-packages/mcedit2/panels/player.py", line 188, in setSelectedPlayerUUID (self is a PlayerPanel)
    self.updateNBTTree()
  File "/usr/lib/python2.7/site-packages/mcedit2/panels/player.py", line 146, in updateNBTTree (self is a PlayerPanel)
    self.nbtEditor.setRootTagRef(self.selectedPlayer)
  File "/usr/lib/python2.7/site-packages/mcedit2/widgets/nbttree/nbteditor.py", line 106, in setRootTagRef (self is a NBTEditorWidget)
    self.treeView.expandToDepth(0)
OverflowError
```
Step:
1. Run
2. Hit edit to open world
3. It sucks. at 37% maybe.
Environment:
Arch Linux x64 latest(testing enabled), MC1.7Forge, Many many mods installed (BC,IC2,MFR,FFM,TE,and more)
Maybe it is a mod related NBT specials. MCEdit need to support mod worlds since it's a reason for crash and locked out worlds...

**Comment by codewarrior0** [comment] 2015-07-24 00:50
Duplicate of #53. See comments.

Can you try a 32-bit build of python and find out whether this is bug PYSIDE-103, or something else?

**Closed by codewarrior0** 2015-07-24 00:50 UTC
