### ISSUE TITLE
error when starting up

### ISSUE THREAD

**Issue by 1blockbelow** [mcedit/mcedit2#207] opened 2016-01-17 23:07 UTC
when i launch mcedit 2 it comes up with a window saying error and

MCEdit version: 2.0.0alpha-921
Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-8-6.2.9200
Processor: Intel64 Family 6 Model 55 Stepping 8, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.0
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.0.0 - Build 10.18.10.3408 (4, 0)
GL_VENDOR: 'Intel'
GL_RENDERER: 'Intel(R) HD Graphics'

Unhandled Exception

Traceback (most recent call last):
File "mcedit2\worldview\worldview.py", line 574, in paintGL (self is a MinimapWorldView)
File "mcedit2\rendering\scenegraph\rendernode.py", line 259, in renderScene

File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
File "mcedit2\rendering\scenegraph\rendernode.py", line 89, in compile (self is a RenderNode)
File "mcedit2\rendering\scenegraph\rendernode.py", line 94, in compile (self is a VertexRenderNode)
File "mcedit2\util\glutils.py", line 145, in compile (self is a DisplayList)
File "mcedit2\util\glutils.py", line 150, in _compile (self is a DisplayList)
File "mcedit2\rendering\scenegraph\rendernode.py", line 108, in draw (self is a VertexRenderNode)
File "mcedit2\rendering\scenegraph\vertex_array.py", line 47, in drawSelf (self is a VertexRenderNode)
File "mcedit2\rendering\scenegraph\vertex_array.py", line 81, in drawArrays (self is a VertexRenderNode)
WindowsError: exception: access violation reading 0x000000000000000C

how do i fix this?

**Comment by codewarrior0** [comment] 2016-01-18 01:37
Duplicate of #110

**Closed by codewarrior0** 2016-01-18 01:37 UTC
