### ISSUE TITLE
"Attempt to call undefined function glActiveTexture, check for bool(glActiveTexture) before calling 

### ISSUE THREAD

**Issue by PNGR** [mcedit/mcedit2#112] opened 2015-06-09 00:22 UTC
log:
[INFO][<string>:131]:MCEdit2 version 2.0.0alpha-450 starting...
[INFO][mcedit2.util.profiler:87]:Decorating <function work at 0x049D72F0> with work
[INFO][OpenGL.acceleratesupport:13]:OpenGL_accelerate module loaded
[INFO][OpenGL.arrays.arraydatatype:270]:Using accelerated ArrayDatatype
[INFO][mcedit2.util.profiler:87]:Decorating <function loadSections at 0x05074870> with SelectionScene
[INFO][mcedit2.util.profiler:87]:Decorating <function __iter__ at 0x050B36F0> with ChunkUpdate
[INFO][mcedit2.util.profiler:87]:Decorating <function buildChunkMeshes at 0x050B36B0> with buildChunkMeshes
[INFO][mcedit2.util.profiler:87]:Decorating <function buildSectionMeshes at 0x050B3770> with buildSectionMeshes
[INFO][mcedit2.util.profiler:87]:Decorating <function __iter__ at 0x050B3FB0> with SectionUpdate
[INFO][mcedit2.util.settings:100]:Loading app settings from C:\Users\Ryan\Desktop\MCEDIT~2.0A~\MCEdit User Data\mcedit2.ini
[INFO][mcedit2.util.profiler:87]:Decorating <function workOnChunk at 0x05394770> with SlicedMesh
[INFO][mcedit2.util.minecraftinstall:205]:Checking install at C:\Users\Ryan\AppData\Roaming\.minecraft
[INFO][mcedit2.util.minecraftinstall:212]:Found versions:
[u'1.7.10', u'1.7.10-Forge10.13.2.1236', u'1.7.10-LiteLoader1.7.10', u'1.7.10-OptiFine_HD_A4', u'1.7.2', u'1.7.2-Forge10.12.0.1024', u'1.7.2-Forge10.12.2.1121', u'1.7.2-Forge10.12.2.1147', u'1.7.2-TMI', u'1.7.5', u'1.7.9', u'1.8', u'1.8-Forge11.14.0.1295-1.8', u'1.8-Forge11.14.1.1334', u'1.8-OptiFine_HD_U_B1', u'1.8.4', u'1.8.4-OptiFine_HD_U_D4']
[INFO][mcedit2.util.minecraftinstall:80]:MCInstall saved settings: [{u'path': u'C:\\Users\\Ryan\\AppData\\Roaming\\.minecraft', u'name': u'(Default)'}]
[WARNING][mcedit2.editorapp:88]:UserFilesDirectory: C:\Users\Ryan\Desktop\MCEDIT~2.0A~\MCEdit User Data
[INFO][mcedit2.editorapp:96]:Loaded translator.
[INFO][mcedit2.editorapp:105]:Loaded stylesheet.
[INFO][mcedit2.editorapp:117]:Loaded main window.
[INFO][mcedit2.editorapp:157]:Loaded panels.
[INFO][mcedit2.editorapp:200]:Loaded debug widgets.
[INFO][mcedit2.editorapp:251]:Loaded menus.
[INFO][mcedit2.worldlist:134]:Size hint: PySide.QtCore.QSize(120, 73)
[INFO][mcedit2.worldlist:135]:Size : PySide.QtCore.QSize(120, 100)
[INFO][mcedit2.worldlist:324]:Scanning C:\Users\Ryan\AppData\Roaming\.minecraft\saves for worlds...
[INFO][mcedit2.util.minecraftinstall:257]:Created ResourceLoader with search path:
C:\Users\Ryan\AppData\Roaming\.minecraft\versions\1.7.10\1.7.10.jar (e6b7a531b95d0c172acb704d1f54d1b3),
C:\Users\Ryan\AppData\Roaming\.minecraft\versions\1.8\1.8.jar (8663a10cecc10eaa683a927ef5371852)
[INFO][mcedit2.worldlist:364]:Loading block models...
[INFO][mcedit2.worldlist:364]:Loading block models 0/1391
[INFO][mcedit2.worldlist:364]:Loading block models 100/1391
[INFO][mcedit2.worldlist:364]:Loading block models 200/1391
[INFO][mcedit2.worldlist:364]:Loading block models 300/1391
[INFO][mcedit2.worldlist:364]:Loading block models 400/1391
[INFO][mcedit2.worldlist:364]:Loading block models 500/1391
[INFO][mcedit2.worldlist:364]:Loading block models 600/1391
[INFO][mcedit2.worldlist:364]:Loading block models 700/1391
[INFO][mcedit2.worldlist:364]:Loading block models 800/1391
[INFO][mcedit2.worldlist:364]:Loading block models 900/1391
[INFO][mcedit2.worldlist:364]:Loading block models 1000/1391
[INFO][mcedit2.worldlist:364]:Loading block models 1100/1391
[INFO][mcedit2.worldlist:364]:Loading block models 1200/1391
[INFO][mcedit2.worldlist:364]:Loading block models 1300/1391
[INFO][mcedit2.rendering.textureatlas:111]:Preloaded 349 textures for world 1_8 Redstone (471 kB)
[INFO][mcedit2.util.qglcontext:20]:OpenGL Version Info:
[INFO][mcedit2.util.qglcontext:35]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_1_1
[INFO][mcedit2.util.qglcontext:35]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_1_2
[INFO][mcedit2.util.qglcontext:35]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_1_3
[INFO][mcedit2.util.qglcontext:35]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_1_4
[INFO][mcedit2.util.qglcontext:35]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_1_5
[INFO][mcedit2.util.qglcontext:35]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_2_0
[INFO][mcedit2.util.qglcontext:52]:Obtained a GL context with this format:
Valid: True
Version: 2.1
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True

Driver info:
GL_VERSION: 2.1.0 - Build 8.15.10.2302
GL_VENDOR: Intel
GL_RENDERER: Intel(R) G45/G43 Express Chipset

[INFO][mcedit2.worldview.worldview:777]:LAYER Blocks VISIBLE True
[INFO][mcedit2.worldview.worldview:777]:LAYER Entities VISIBLE True
[INFO][mcedit2.worldview.worldview:777]:LAYER Items VISIBLE True
[INFO][mcedit2.worldview.worldview:777]:LAYER TileEntities VISIBLE True
[INFO][mcedit2.worldview.worldview:777]:LAYER TileTicks VISIBLE True
[INFO][mcedit2.rendering.textureatlas:205]:Terrain atlas created for world 1_8 Redstone (471/505 kB)
[INFO][mcedit2.rendering.textureatlas:206]:Cooking quads for 1238 models...
[INFO][mcedit2.worldview.worldview:149]:Changing MinimapWorldView(u'None') to dimension WorldEditorDimension(dimName='', adapter=AnvilWorldAdapter(u'C:\\Users\\Ryan\\AppData\\Roaming\\.minecraft\\saves\\1_8 Redstone'))
[INFO][mcedit2.rendering.chunkloader:131]:Added: client MinimapWorldView(u'1_8 Redstone: ')
[INFO][mcedit2.worldlist:384]:Centering on single-player player.
[INFO][mcedit2.worldlist:403]:Switched world view
[INFO][mcedit2.editorapp:261]:Loaded world list.
[INFO][mcedit2.editorapp:280]:Loaded status bar.
[INFO][mcedit2.editorapp:562]:Updating recent files menu: (0) []
[INFO][mcedit2.editorapp:287]:Loaded settings.
[WARNING][mcedit2.widgets.configureblocksdialog:119]:Failed to read definitions file defined_blocks.json
[INFO][mcedit2.editorapp:308]:Loaded app dialogs.
[INFO][mcedit2.editorapp:316]:Loading timer started
[INFO][mcedit2.editorapp:326]:Finding plugins
[INFO][mcedit2.plugins:199]:Loading plugins from C:\Users\Ryan\Desktop\MCEDIT~2.0A~\MCEdit User Data\plugins
[INFO][mcedit2.plugins:111]:Trying to load plugin from koch.py
[INFO][mcedit2.plugins:122]:Loaded koch.py (Koch Snowflake)
[INFO][mcedit2.plugins:111]:Trying to load plugin from storagedrawers.py
[INFO][mcedit2.plugins:122]:Loaded storagedrawers.py (storagedrawers)
[INFO][mcedit2.plugins:111]:Trying to load plugin from city.py
[INFO][mcedit2.plugins:122]:Loaded city.py (GFX: City)
[INFO][mcedit2.editorapp:342]:Opening worlds from command line.
[INFO][mceditlib.worldeditor:420]:Scanning for regions in C:\Users\Ryan\AppData\Roaming\.minecraft\saves\1_8 Redstone...
[INFO][mceditlib.worldeditor:429]:Dim : Found 1343 chunks in 0.26 seconds.
[INFO][mcedit2.worldlist:416]:Removing view from WorldListWidget
[INFO][mcedit2.util.minecraftinstall:257]:Created ResourceLoader with search path:
C:\Users\Ryan\AppData\Roaming\.minecraft\versions\1.7.10\1.7.10.jar (e6b7a531b95d0c172acb704d1f54d1b3),
C:\Users\Ryan\AppData\Roaming\.minecraft\versions\1.8\1.8.jar (8663a10cecc10eaa683a927ef5371852)
[INFO][mcedit2.worldlist:364]:Loading block models...
[INFO][mcedit2.worldlist:364]:Loading block models 0/1391
[INFO][mcedit2.worldlist:364]:Loading block models 100/1391
[INFO][mcedit2.worldlist:364]:Loading block models 200/1391
[INFO][mcedit2.worldlist:364]:Loading block models 300/1391
[INFO][mcedit2.worldlist:364]:Loading block models 400/1391
[INFO][mcedit2.worldlist:364]:Loading block models 500/1391
[INFO][mcedit2.worldlist:364]:Loading block models 600/1391
[INFO][mcedit2.worldlist:364]:Loading block models 700/1391
[INFO][mcedit2.worldlist:364]:Loading block models 800/1391
[INFO][mcedit2.worldlist:364]:Loading block models 900/1391
[INFO][mcedit2.worldlist:364]:Loading block models 1000/1391
[INFO][mcedit2.worldlist:364]:Loading block models 1100/1391
[INFO][mcedit2.worldlist:364]:Loading block models 1200/1391
[INFO][mcedit2.worldlist:364]:Loading block models 1300/1391
[INFO][mcedit2.rendering.textureatlas:111]:Preloaded 349 textures for world 1_8 Redstone (471 kB)
[INFO][mcedit2.util.qglcontext:20]:OpenGL Version Info:
[INFO][mcedit2.util.qglcontext:35]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_1_1
[INFO][mcedit2.util.qglcontext:35]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_1_2
[INFO][mcedit2.util.qglcontext:35]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_1_3
[INFO][mcedit2.util.qglcontext:35]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_1_4
[INFO][mcedit2.util.qglcontext:35]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_1_5
[INFO][mcedit2.util.qglcontext:35]:PySide.QtOpenGL.QGLFormat.OpenGLVersionFlag.OpenGL_Version_2_0
[INFO][mcedit2.util.qglcontext:52]:Obtained a GL context with this format:
Valid: True
Version: 2.1
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True

Driver info:
GL_VERSION: 2.1.0 - Build 8.15.10.2302
GL_VENDOR: Intel
GL_RENDERER: Intel(R) G45/G43 Express Chipset

[INFO][mcedit2.worldview.worldview:777]:LAYER Blocks VISIBLE True
[INFO][mcedit2.worldview.worldview:777]:LAYER Entities VISIBLE True
[INFO][mcedit2.worldview.worldview:777]:LAYER Items VISIBLE True
[INFO][mcedit2.worldview.worldview:777]:LAYER TileEntities VISIBLE True
[INFO][mcedit2.worldview.worldview:777]:LAYER TileTicks VISIBLE True
[INFO][mcedit2.rendering.textureatlas:205]:Terrain atlas created for world 1_8 Redstone (471/505 kB)
[INFO][mcedit2.rendering.textureatlas:206]:Cooking quads for 1238 models...
[INFO][mcedit2.worldview.worldview:149]:Changing MinimapWorldView(u'None') to dimension WorldEditorDimension(dimName='', adapter=AnvilWorldAdapter(u'C:\\Users\\Ryan\\AppData\\Roaming\\.minecraft\\saves\\1_8 Redstone'))
[INFO][mcedit2.rendering.chunkloader:131]:Added: client MinimapWorldView(u'1_8 Redstone: ')
[INFO][mcedit2.worldlist:384]:Centering on single-player player.
[INFO][mcedit2.worldlist:403]:Switched world view
[INFO][mcedit2.rendering.loadablechunks:90]:Making checkerboard texture...
[INFO][mceditlib.worldeditor:420]:Scanning for regions in C:\Users\Ryan\AppData\Roaming\.minecraft\saves\1_8 Redstone...
[INFO][mceditlib.worldeditor:429]:Dim : Found 1343 chunks in 0.21 seconds.
[ERROR][<string>:153]:Unhandled Exception: 
	Attempt to call an undefined function glActiveTexture, check for bool(glActiveTexture) before calling
Traceback (most recent call last):
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\mcedit2.worldview.worldview", line 493, in paintGL (self is a MinimapWorldView)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 393, in renderScene  
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a MatrixRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a RenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 90, in compile (self is a DepthOffsetRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 93, in compile (self is a TextureAtlasRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\mcedit2.util.glutils", line 149, in compile (self is a DisplayList)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\mcedit2.util.glutils", line 162, in _compile (self is a DisplayList)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 122, in draw (self is a TextureAtlasRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\mcedit2.rendering.rendergraph", line 143, in enter (self is a TextureAtlasRenderNode)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-32\winbuild\build\build\mcedit2\out00-PYZ.pyz\OpenGL.platform.baseplatform", line 407, in __call__  
NullFunctionError: Attempt to call an undefined function glActiveTexture, check for bool(glActiveTexture) before calling

**Comment by PNGR** [comment] 2015-06-09 00:23
This is on every Alpha version I try to use...

**Comment by codewarrior0** [comment] 2015-06-09 03:04
Does this happen with both 32-bit and 64-bit versions?

**Comment by PNGR** [comment] 2015-06-09 11:15
Yes, the 64-bit versions have the same problem.

**Comment by codewarrior0** [comment] 2015-06-09 14:27
Duplicate of #112

**Closed by codewarrior0** 2015-06-09 14:27 UTC
