### ISSUE TITLE
UnicodeDecodeError in mimetypes on Windows

### ISSUE THREAD

**Issue by Nikdoge** [mcedit/mcedit2#47] opened 2015-03-23 15:02 UTC
![default](https://cloud.githubusercontent.com/assets/11614920/6782622/4c3e9c2c-d186-11e4-8f85-826f89275bc6.png)

Windows 7, 64-bit

*I don't have user Rio on my computer, my user is "ааа" in Cyrillic alphabet.

**Comment by codewarrior0** [comment] 2015-03-25 10:12
This looks like a bug in the `mimetypes` module, a component of Python. There may not be anything I can do about it.

**Comment by tiobane** [comment] 2015-05-12 14:03
Have the same proble, win 8.1 64 bit, tested several installers. System is almost newly set up, MC Edit worked without problems until my system reset.

**Comment by codewarrior0** [comment] 2015-05-14 12:07
I think this is actually a packaging error. The stack trace corresponds to the `mimetypes` module of Python 2.7.3, but I am in fact using 2.7.9. I've cleaned out all of the .pyc/.pyo files from my Python installation for the next build.

**Comment by codewarrior0** [comment] 2015-05-26 21:47
Can any of you reproduce the issue with build 404 or later?

**Comment by ishitatsuyuki** [comment] 2015-07-24 00:16
I reproduced it with another part: (* this one is packaged to system, Arch Linux x64)
```
[ERROR][main.py:153]:Unhandled Exception: 
        'ascii' codec can't decode byte 0xc2 in position 21: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/bin/mcedit2", line 9, in <module>  
    load_entry_point('mcedit2==2.0.0a1.dev0', 'console_scripts', 'mcedit2')()
  File "/usr/lib/python2.7/site-packages/mcedit2/main.py", line 167, in main  
    app = startup()
  File "/usr/lib/python2.7/site-packages/mcedit2/util/profiler.py", line 65, in _wrapper (self is a Profiler)
    return func(*a, **kw)
  File "/usr/lib/python2.7/site-packages/mcedit2/main.py", line 144, in startup  
    editorApp = MCEditApp(sys.argv)
  File "/usr/lib/python2.7/site-packages/mcedit2/editorapp.py", line 259, in __init__ (self is a MCEditApp)
    self.worldList = WorldListWidget(mainWindow)
  File "/usr/lib/python2.7/site-packages/mcedit2/worldlist.py", line 250, in __init__ (self is a WorldListWidget)
    self.reloadList()
  File "/usr/lib/python2.7/site-packages/mcedit2/worldlist.py", line 344, in reloadList (self is a WorldListWidget)
    self.showWorld(self.worldListModel.worlds[0][0])
  File "/usr/lib/python2.7/site-packages/mcedit2/worldlist.py", line 383, in showWorld (self is a WorldListWidget)
    self.setWorldView(MinimapWorldView(dim, textureAtlas))
  File "/usr/lib/python2.7/site-packages/mcedit2/worldview/minimap.py", line 152, in __init__ (self is a MinimapWorldView)
    WorldView.__init__(self, *a, **kw)
  File "/usr/lib/python2.7/site-packages/mcedit2/worldview/worldview.py", line 101, in __init__ (self is a MinimapWorldView)
    validateQGLContext(self.context())
  File "/usr/lib/python2.7/site-packages/mcedit2/util/qglcontext.py", line 67, in validateQGLContext  
    detailedText += "GL_RENDERER: %s\n" % GL.glGetString(GL.GL_RENDERER)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 21: ordinal not in range(128)
```

**Comment by codewarrior0** [comment] 2015-07-24 00:53
Why is your driver returning non-ASCII for GL_RENDERER?

Try and change %s to %r and see what happens.

**Comment by codewarrior0** [comment] 2015-09-08 10:39
Closing as fixed. This was a packaging error for Windows. The decode error in validateQGLContext was fixed elsewhere.

**Closed by codewarrior0** 2015-09-08 10:39 UTC
Labels: bug, external
